name: Update Spotify Playlist

on:
  schedule:
    # Berjalan setiap 6 jam
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dephraiim/spotify-readme-action@main
        with:
          spotify_client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          spotify_client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          spotify_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          playlist_id: 4Awn3g2DGRiI9I4I2n5L5u
