name: Update Spotify Top Tracks

on:
  schedule:
    # Berjalan setiap 6 jam
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Anmol-Baranwal/spotify-top-tracks-action@v1.2.1
        with:
          spotify_client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          spotify_client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          spotify_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          comment_tag_name: SPOTIFY-TOP-TRACKS
