name: Update Spotify README

on:
  schedule:
    - cron: '*/10 * * * *' # Setiap 10 menit
  workflow_dispatch:

jobs:
  update-readme:
    name: Spotify Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Spotify Now Playing
        uses: kittinan/spotify-github-profile@latest
        with:
          client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}

      - name: Commit & Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "update spotify playing" || echo "No changes to commit"
          git push
