name: Update Spotify Top Tracks

on:
  schedule:
    # Berjalan setiap 6 jam
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/top-tracks-unwrapped@v1
        with:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          TARGET_COMMENT: "SPOTIFY-TOP-TRACKS"
          TIME_RANGE: "long_term"
          TRACKS_COUNT: 5
